[project]
name = "hf-agent-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=0.34.4",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "smolagents==1.13.0",
]
